### ISSUE TITLE
java.lang.NoSuchMethodError: 'org.jaudiolibs.jnajack.JackClient org.openstatic.MIDIBridge.access$0(org.openstatic.MIDIBridge)'

### ISSUE THREAD

**Issue by guysoft** [xitiomet/jack-rtp-midi-bridge#4]
Hey, tried to send a note and got this error:
```
java.lang.NoSuchMethodError: 'org.jaudiolibs.jnajack.JackClient org.openstatic.MIDIBridge.access$0(org.openstatic.MIDIBridge)'
```
Anyd idea what is going on?

Using Ubuntu 23.04 and pipewire 
Full log output:

```
Possible Local Address:/192.168.2.131
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "pool-2-thread-2" java.lang.NoSuchMethodError: 'org.jaudiolibs.jnajack.JackClient org.openstatic.MIDIBridge.access$0(org.openstatic.MIDIBridge)'
        at org.openstatic.MIDIBridge$2.onMidiMessage(MIDIBridge.java:141)
        at io.github.leovr.rtipmidi.session.AppleMidiSession.onMidiMessage(AppleMidiSession.java:47)
        at io.github.leovr.rtipmidi.session.AppleMidiSessionServer.onMidiMessage(AppleMidiSessionServer.java:265)
        at io.github.leovr.rtipmidi.handler.AppleMidiMessageHandler.handleMessage(AppleMidiMessageHandler.java:92)
        at io.github.leovr.rtipmidi.handler.AppleMidiMessageHandler.handle(AppleMidiMessageHandler.java:82)
        at io.github.leovr.rtipmidi.session.AppleMidiSessionServer$1.run(AppleMidiSessionServer.java:123)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Exception in thread "pool-2-thread-3" java.lang.NoSuchMethodError: 'org.jaudiolibs.jnajack.JackClient org.openstatic.MIDIBridge.access$0(org.openstatic.MIDIBridge)'
        at org.openstatic.MIDIBridge$2.onMidiMessage(MIDIBridge.java:141)
        at io.github.leovr.rtipmidi.session.AppleMidiSession.onMidiMessage(AppleMidiSession.java:47)
        at io.github.leovr.rtipmidi.session.AppleMidiSessionServer.onMidiMessage(AppleMidiSessionServer.java:265)
        at io.github.leovr.rtipmidi.handler.AppleMidiMessageHandler.handleMessage(AppleMidiMessageHandler.java:92)
        at io.github.leovr.rtipmidi.handler.AppleMidiMessageHandler.handle(AppleMidiMessageHandler.java:82)
        at io.github.leovr.rtipmidi.session.AppleMidiSessionServer$1.run(AppleMidiSessionServer.java:123)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Exception in thread "pool-2-thread-4" java.lang.NoSuchMethodError: 'org.jaudiolibs.jnajack.JackClient org.openstatic.MIDIBridge.access$0(org.openstatic.MIDIBridge)'
        at org.openstatic.MIDIBridge$2.onMidiMessage(MIDIBridge.java:141)
        at io.github.leovr.rtipmidi.session.AppleMidiSession.onMidiMessage(AppleMidiSession.java:47)
        at io.github.leovr.rtipmidi.session.AppleMidiSessionServer.onMidiMessage(AppleMidiSessionServer.java:265)
        at io.github.leovr.rtipmidi.handler.AppleMidiMessageHandler.handleMessage(AppleMidiMessageHandler.java:92)
        at io.github.leovr.rtipmidi.handler.AppleMidiMessageHandler.handle(AppleMidiMessageHandler.java:82)
        at io.github.leovr.rtipmidi.session.AppleMidiSessionServer$1.run(AppleMidiSessionServer.java:123)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Exception in thread "pool-2-thread-5" java.lang.NoSuchMethodError: 'org.jaudiolibs.jnajack.JackClient org.openstatic.MIDIBridge.access$0(org.openstatic.MIDIBridge)'
        at org.openstatic.MIDIBridge$2.onMidiMessage(MIDIBridge.java:141)
        at io.github.leovr.rtipmidi.session.AppleMidiSession.onMidiMessage(AppleMidiSession.java:47)
        at io.github.leovr.rtipmidi.session.AppleMidiSessionServer.onMidiMessage(AppleMidiSessionServer.java:265)
        at io.github.leovr.rtipmidi.handler.AppleMidiMessageHandler.handleMessage(AppleMidiMessageHandler.java:92)
        at io.github.leovr.rtipmidi.handler.AppleMidiMessageHandler.handle(AppleMidiMessageHandler.java:82)
        at io.github.leovr.rtipmidi.session.AppleMidiSessionServer$1.run(AppleMidiSessionServer.java:123)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Exception in thread "pool-2-thread-6" java.lang.NoSuchMethodError: 'org.jaudiolibs.jnajack.JackClient org.openstatic.MIDIBridge.access$0(org.openstatic.MIDIBridge)'
        at org.openstatic.MIDIBridge$2.onMidiMessage(MIDIBridge.java:141)
        at io.github.leovr.rtipmidi.session.AppleMidiSession.onMidiMessage(AppleMidiSession.java:47)
        at io.github.leovr.rtipmidi.session.AppleMidiSessionServer.onMidiMessage(AppleMidiSessionServer.java:265)
        at io.github.leovr.rtipmidi.handler.AppleMidiMessageHandler.handleMessage(AppleMidiMessageHandler.java:92)
        at io.github.leovr.rtipmidi.handler.AppleMidiMessageHandler.handle(AppleMidiMessageHandler.java:82)
        at io.github.leovr.rtipmidi.session.AppleMidiSessionServer$1.run(AppleMidiSessionServer.java:123)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Exception in thread "pool-2-thread-7" java.lang.NoSuchMethodError: 'org.jaudiolibs.jnajack.JackClient org.openstatic.MIDIBridge.access$0(org.openstatic.MIDIBridge)'
        at org.openstatic.MIDIBridge$2.onMidiMessage(MIDIBridge.java:141)
        at io.github.leovr.rtipmidi.session.AppleMidiSession.onMidiMessage(AppleMidiSession.java:47)
        at io.github.leovr.rtipmidi.session.AppleMidiSessionServer.onMidiMessage(AppleMidiSessionServer.java:265)
        at io.github.leovr.rtipmidi.handler.AppleMidiMessageHandler.handleMessage(AppleMidiMessageHandler.java:92)
        at io.github.leovr.rtipmidi.handler.AppleMidiMessageHandler.handle(AppleMidiMessageHandler.java:82)
        at io.github.leovr.rtipmidi.session.AppleMidiSessionServer$1.run(AppleMidiSessionServer.java:123)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Exception in thread "pool-2-thread-8" java.lang.NoSuchMethodError: 'org.jaudiolibs.jnajack.JackClient org.openstatic.MIDIBridge.access$0(org.openstatic.MIDIBridge)'
        at org.openstatic.MIDIBridge$2.onMidiMessage(MIDIBridge.java:141)
        at io.github.leovr.rtipmidi.session.AppleMidiSession.onMidiMessage(AppleMidiSession.java:47)
        at io.github.leovr.rtipmidi.session.AppleMidiSessionServer.onMidiMessage(AppleMidiSessionServer.java:265)
        at io.github.leovr.rtipmidi.handler.AppleMidiMessageHandler.handleMessage(AppleMidiMessageHandler.java:92)
        at io.github.leovr.rtipmidi.handler.AppleMidiMessageHandler.handle(AppleMidiMessageHandler.java:82)
        at io.github.leovr.rtipmidi.session.AppleMidiSessionServer$1.run(AppleMidiSessionServer.java:123)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by guysoft** [comment]
Update: workaround - compiling from source seems to have solved the issue for me

**Comment by xitiomet** [comment]
Sorry just saw this, glad you were able to find a work around.
